New updates

diff --git a/bash/functions b/bash/functions
--- a/bash/functions
+++ b/bash/functions
@@ -430,3 +430,22 @@ cdnotes() { cd ~/Notes ;}
 #     command lein "$@"
 #   fi
 # }
+
+
+# Code Review
+# This will open the diff to master (the same diff as in a pull request). If you
+# pass a second argument, it'll use that branch as a base instead.
+review() {
+  local default_branch=$(git rev-parse --abbrev-ref HEAD)
+  local branch="${1:-$default_branch}"
+  local base="${2:-master}"
+
+  git fetch origin $base $branch
+
+  # This typically fails if you have stashed changes.
+  if ! git checkout $branch; then
+    return 1
+  fi
+
+  nvim -c "let g:gitgutter_diff_base = 'origin/$base'" -c ":e!" $(git diff --name-only origin/$base...$branch)
+}
